# Generated by Django 3.0.8 on 2020-07-13 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(verbose_name='Логин')),
                ('spent_money', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Cумма')),
            ],
        ),
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название камня')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.TextField(verbose_name='Логин')),
                ('item', models.TextField(verbose_name='Наименование товара')),
                ('total', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Сумма сделки')),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Количество товара')),
                ('date', models.DateTimeField(verbose_name='Время')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Buyer')),
            ],
        ),
        migrations.AddField(
            model_name='buyer',
            name='gems',
            field=models.ManyToManyField(to='main.Stone'),
        ),
    ]
